# Generated by Django 2.0.5 on 2018-06-11 14:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180611_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
