# Generated by Django 2.0.5 on 2018-06-11 14:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180611_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
