language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script: python manage.py test 
notifications:
  email:
    recipients:
      - tanveerobjects@.com
    on_success: always # default: change
    on_failure: always # default: always